// useSupabase is intentionally not exported — internal to this package only.
// Consumers get the client via SupabaseProvider, not by calling useSupabase directly.
export { SupabaseProvider }        from './SupabaseContext'

export { useSession }              from './useSession'
export { useSignIn }               from './useSignIn'
export { useSignOut }              from './useSignOut'
export { useTripData }             from './useTripData'
export { useJoinTrip }             from './useJoinTrip'
export { useRateActivity }         from './useRateActivity'
export { useAddActivity }          from './useAddActivity'
export { useCompatibilityMatrix }  from './useCompatibilityMatrix'
export { useActivityFilter }       from './useActivityFilter'
export { useActivityActions }      from './useActivityActions'
export { useUserTrips }            from './useUserTrips'
export { useCreateTrip }           from './useCreateTrip'
export { useUpdateMemberDates }    from './useUpdateMemberDates'
export { useUpdateTrip }           from './useUpdateTrip'
export { useRegenerateInvite }     from './useRegenerateInvite'
export { useDeleteTrip }           from './useDeleteTrip'
export { useRemoveMember }         from './useRemoveMember'
export { useOnboarding }           from './useOnboarding'
export { useStopActions }          from './useStopActions'
export { useUndoAction }           from './useUndoAction'
export { useCrewRows }             from './useCrewRows'
export { usePresence }             from './usePresence'
export { useConvergence }          from './useConvergence'
export type { PresenceModel }      from './usePresence'
export type { ConvergenceModel }   from './useConvergence'
export * from './planEngine'
